---
- name: forbid SSH root login  
  lineinfile: destfile=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify:
    - restart ssh
    
- name: forbid SSH password login  
  lineinfile: destfile=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify:
    - restart ssh    
    
- name: update apt cache  
  apt: update_cache=yes cache_valid_time=3600
    
    
- name: install common packages
  apt: pkg={{ item }} state=latest  
  with_items:
    - build-essential
    - git
    - tree
    - vim
    - psmisc
    - fail2ban
    - chkrootkit
    - ufw    
    - zip
    - rsync
    - wget  
    - screen
    - p7zip-full

- name: Safely upgrade installed packages
  apt: upgrade=safe        
  