CREATE TABLE Timezones (id INT NOT NULL, user_id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id));
CREATE INDEX IDX_F7A34AFDA76ED395 ON Timezones (user_id);
CREATE TABLE Users (id INT NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, role INT NOT NULL, PRIMARY KEY(id));
CREATE SEQUENCE Timezones_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE Users_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
ALTER TABLE Timezones ADD CONSTRAINT FK_F7A34AFDA76ED395 FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
