---
- name: Create selenium dir
  file: path=/usr/lib/selenium state=directory mode=755 

- name: Download the latest selenium jar
  get_url: 
    url: http://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.0.jar
    dest: /usr/lib/selenium/selenium-server.jar
    mode: 755
    
- name: Install required packages
  apt: name=openjdk-7-jre-headless state=present
  
- name: Create log dir
  file: path=/var/log/selenium state=directory mode=0644 
  
- name: copy upstart daemons
  copy: src={{ item }}.conf dest=/etc/init/{{ item }}.conf
  with_items:    
    - selenium

- name: Ensure dameons are running
  service: name={{item}} state=restarted
  with_items:
    - selenium