---
- name: ensure database user exists
  become_user: postgres    
  postgresql_user:    
    user: "mdtimezone"
    password: "mdtimezone"
    role_attr_flags: "LOGIN"
    state: present            
    
- name: ensure database exists 
  become_user: postgres    
  postgresql_db:
    db: "mdtimezone"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    owner: mdtimezone
    state: present    

- name: read list of tables in db
  shell: psql -c "\\d" mdtimezone
  become_user: postgres
  register: app_tables

- name: import default dump     
  command: psql -d 'postgresql://mdtimezone:mdtimezone@localhost/mdtimezone' -f {{item}}  
  when: app_tables.stdout.find('users') == -1
  with_items:
    - /app/db/full-metadata.sql
    - /app/db/initial-insert.sql
  