---
- name: install needed php packages
  apt: pkg={{ item }} state=present
  with_items:
    - php7.0-pgsql
    - php7.0-sqlite3
    - php7.0-json
    - php7.0-xml
    - php7.0-curl
  

# using touch+cp instead of the copy module because on windows it fails for
# shared dirs (see https://github.com/ansible/ansible/issues/9526)  
- name: create config file
  file: path=/app/local/config-vagrant.php state=touch
- name: copy the config file to temp dir
  template: src=config-vagrant.php dest=/tmp/config-vagrant.php
- name: Copy the config file to shared folder location 
  command: cp /tmp/config-vagrant.php /app/local/config-vagrant.php
    
#- name: copy config file if does not exist
#  template: src=config-vagrant.php dest=/app/src/local/config-vagrant.php    
        
- name: Run composer to install dependencies
  become: no
  composer: command=install working_dir=/app
    